common: &common
  - "flake.nix"
  - "flake.lock"
  - ".github/filters.yaml"
  - ".github/workflows/all.yaml"
  - ".github/workflows/intersphinx.yaml"
docs-shell:
  - *common
  - "docs/**/*.nix"
  - "docs/pyproject/**"
docs:
  - *common
  - "docs/**"
software:
  - *common
  - "software/**"
  # ignore script updates
  - "!software/scripts/**"
  - "!software/ros_ws/colcon/**"
formatter-config:
  - flake.nix
  - treefmt.nix
packages:
  - "software/**/package.xml"
