# Automatically generated by: ros2nix --output-dir=/home/bocho0600/roar/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  interfaces,
  nlohmann_json,
  rclcpp,
  tf2,
  tf2-geometry-msgs,
  tf2-ros,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-arena-server";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/arena_server;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    interfaces
    nlohmann_json
    rclcpp
    tf2
    tf2-geometry-msgs
    tf2-ros
    visualization-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Owns the Lunabotics arena layout and estimates map -&gt; odom from the rail fiducials";
    license = with lib.licenses; [ mit ];
  };
}
