# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  generate-parameter-library,
  liblapack,
  moveit-core,
  orocos-kdl-vendor,
  pluginlib,
  rclcpp,
  tf2-eigen,
  tf2-kdl,
}:
buildRosPackage rec {
  pname = "ros-jazzy-arm-ikfast-plugin";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/arm_ikfast_plugin;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    generate-parameter-library
    liblapack
    moveit-core
    orocos-kdl-vendor
    pluginlib
    rclcpp
    tf2-eigen
    tf2-kdl
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Generated IKFast (TranslationZAxisAngle4D) kinematics plugin for the
    arm arm group. Produced by
    Max’s arm_control generation script -- do not hand-edit;
    re-run the script instead.";
    license = with lib.licenses; [ mit ];
  };
}
