# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  arena-server,
  bievr-lio-ros2,
  fast-lio,
  footprint-broadcaster,
  global-traversability,
  health-check,
  navigation2,
  ohm-mapping,
  rclcpp,
  robot-localization,
  rviz-plugins,
  sensors,
  slam-toolbox,
  vision,
  watchdog,
  xacro,
}:
buildRosPackage rec {
  pname = "ros-jazzy-autonomy-bringup";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/autonomy_bringup;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    arena-server
    bievr-lio-ros2
    fast-lio
    footprint-broadcaster
    global-traversability
    health-check
    navigation2
    ohm-mapping
    rclcpp
    robot-localization
    rviz-plugins
    sensors
    slam-toolbox
    vision
    watchdog
    xacro
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROAR autonomy_bringup software control stack";
    license = with lib.licenses; [ mit ];
  };
}
