# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  hi-can-raw,
}:
buildRosPackage rec {
  pname = "ros-jazzy-can-logger";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/can_logger;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ hi-can-raw ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Logs every CAN frame seen on an interface to a single CSV file, buffering 15000 lines in memory between writes.";
    license = with lib.licenses; [ mit ];
  };
}
