# Automatically generated by: ros2nix --output-dir=/home/innario/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  hi-can-raw,
  interfaces,
  nlohmann_json,
  rclcpp,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-can-if";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/can_if;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    hi-can-raw
    interfaces
    nlohmann_json
    rclcpp
    sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Payload-specific nodes and launch files for the Perseus Rover.";
    license = with lib.licenses; [ mit ];
  };
}
