# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  hi-can-raw,
}:
buildRosPackage rec {
  pname = "ros-jazzy-can-diag";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/can_diag;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ hi-can-raw ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Generic hi-can diagnostic CLI: send an arbitrary CAN packet (RTR request or data frame) to any hi-can address and print/decode whatever response arrives.";
    license = with lib.licenses; [ mit ];
  };
}
