# Automatically generated by: ros2nix --output-dir=/home/bocho0600/roar/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{ lib, buildRosPackage, ament-cmake, ament-lint-auto, ament-lint-common, grid-map-core, nav-msgs, pcl-conversions, rclcpp, sensor-msgs }:
buildRosPackage rec {
  pname = "ros-jazzy-global-traversability";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/global_traversability;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ grid-map-core nav-msgs pcl-conversions rclcpp sensor-msgs ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Builds a terrain-aware global costmap from the 3D lidar map, replacing a 2D-SLAM-only costmap source";
    license = with lib.licenses; [ mit ];
  };
}
