# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  grid-map-core,
  local-traversability,
  nav-msgs,
  pcl-conversions,
  rclcpp,
  sensor-msgs,
  tf2,
  tf2-eigen,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-global-traversability";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/global_traversability;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    grid-map-core
    local-traversability
    nav-msgs
    pcl-conversions
    rclcpp
    sensor-msgs
    tf2
    tf2-eigen
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Builds a persistent, self-clearing terrain costmap from the raw lidar scan by height difference";
    license = with lib.licenses; [ mit ];
  };
}
