# Automatically generated by: ros2nix --output-dir=/home/bocho0600/roar/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  interfaces,
  rclcpp,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-health-check";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/health_check;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    interfaces
    rclcpp
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Topic rate and staleness monitoring for the sensing and estimation stack";
    license = with lib.licenses; [ mit ];
  };
}
