# Automatically generated by: ros2nix --output-dir=/home/maximus/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-cmake-gen-version-h,
  ament-cmake-gmock,
  ament-cmake-gtest,
  controller-manager-msgs,
  hector-transmission-interface-msgs,
  pluginlib,
  rclcpp,
  ros2-control-cmake,
  sensor-msgs,

  std-msgs,
  transmission-interface,
}:
buildRosPackage rec {
  pname = "ros-jazzy-hector-transmission-interface";
  version = "0.0.0";

  src = ./../../../../software/ros_ws/src/hector_transmission_interface/hector_transmission_interface;

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    ros2-control-cmake
  ];
  checkInputs = [
    ament-cmake-gmock
    ament-cmake-gtest
  ];

  propagatedBuildInputs = [
    ament-cmake-gen-version-h
    controller-manager-msgs
    hector-transmission-interface-msgs
    pluginlib
    rclcpp
    sensor-msgs
    std-msgs
    transmission-interface
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "TODO";
    license = with lib.licenses; [ "TODO-CATKIN-PACKAGE-LICENSE" ];
  };
}
