# Automatically generated by: ros2nix --output-dir=/home/maximus/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-hector-transmission-interface-msgs";
  version = "0.0.0";

  src = ./../../../../software/ros_ws/src/hector_transmission_interface/hector_transmission_interface_msgs;

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  propagatedBuildInputs = [
    rosidl-default-runtime
    sensor-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "TODO";
    license = with lib.licenses; [ "TODO-CATKIN-PACKAGE-LICENSE" ];
  };
}
