# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  interfaces,
  launch,
  launch-ros,
  rclcpp,
}:
buildRosPackage rec {
  pname = "ros-jazzy-link-monitor";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/link_monitor;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    interfaces
    launch
    launch-ros
    rclcpp
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Measures throughput and reachability of the radio link to the rover";
    license = with lib.licenses; [ mit ];
  };
}
