# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  behaviortree-cpp,
  geometry-msgs,
  interfaces,
  nav2-behavior-tree,
  rclcpp,
  std-srvs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-mission-bt-server";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/mission_bt_server;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    behaviortree-cpp
    geometry-msgs
    interfaces
    nav2-behavior-tree
    rclcpp
    std-srvs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Runs a small behaviour tree - request a safe zone waypoint from arena_server, then drive there via nav2's NavigateToPose - behind two plain services for the RViz mission panel";
    license = with lib.licenses; [ mit ];
  };
}
