# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  nav-msgs,
  ohm,
  rclcpp,
  sensor-msgs,
  tf2,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-ohm-mapping";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/ohm_mapping;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    nav-msgs
    ohm
    rclcpp
    sensor-msgs
    tf2
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 front end for CSIRO OHM: streams a registered LiDAR cloud into a probabilistic 3D occupancy map and publishes its 2.5D heightmap, including virtual surfaces inferred over unobserved ground";
    license = with lib.licenses; [ mit ];
  };
}
