# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  actuator-msgs,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  controller-manager,
  hardware-interface,
  hi-can-raw,
  joint-state-broadcaster,
  pluginlib,
  rclcpp,
  rclcpp-lifecycle,
  robot-state-publisher,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-payloads";
  version = "0.2.1";

  src = ./../../../../software/ros_ws/src/payloads;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    actuator-msgs
    controller-manager
    hardware-interface
    hi-can-raw
    joint-state-broadcaster
    pluginlib
    rclcpp
    rclcpp-lifecycle
    robot-state-publisher
    sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Payload-specific nodes and launch files for the Perseus Rover.";
    license = with lib.licenses; [ mit ];
  };
}
