# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-cmake-cppcheck,
  ament-cmake-cpplint,
  ament-cmake-flake8,
  ament-cmake-lint-cmake,
  ament-cmake-pep257,
  ament-cmake-uncrustify,
  ament-cmake-xmllint,
  ament-lint-auto,
  laser-geometry,
  launch,
  launch-ros,
  message-filters,
  rclcpp,
  rclcpp-components,
  sensor-msgs,
  tf2,
  tf2-ros,
  tf2-sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-pcl-to-lsr";
  version = "2.0.2";

  src = ./../../../../software/ros_ws/src/pcl_to_lsr;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-cmake-cppcheck
    ament-cmake-cpplint
    ament-cmake-flake8
    ament-cmake-lint-cmake
    ament-cmake-pep257
    ament-cmake-uncrustify
    ament-cmake-xmllint
    ament-lint-auto
  ];
  propagatedBuildInputs = [
    laser-geometry
    launch
    launch-ros
    message-filters
    rclcpp
    rclcpp-components
    sensor-msgs
    tf2
    tf2-ros
    tf2-sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Converts a 3D Point Cloud into a 2D laser scan. This is useful for making devices like the Kinect appear like a laser scanner for 2D-based algorithms (e.g. laser-based SLAM).";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
