# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-cmake-gtest,
  gz-ros2-control,
  perseus,
  ros-gz-bridge,
  ros-gz-image,
  ros-gz-interfaces,
  ros-gz-sim,
  rosbridge-server,
  twist-mux,
  twist-stamper,
  yaml-cpp-vendor,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-simulation";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/perseus_simulation;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-cmake-gtest
    yaml-cpp-vendor
  ];
  propagatedBuildInputs = [
    gz-ros2-control
    perseus
    ros-gz-bridge
    ros-gz-image
    ros-gz-interfaces
    ros-gz-sim
    rosbridge-server
    twist-mux
    twist-stamper
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Package for simulating the Perseus rover using Gazebo.";
    license = with lib.licenses; [ mit ];
  };
}
