# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  nav2-msgs,
  perseus-interfaces,
  rclcpp,
  rclcpp-action,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-autonomy-bridge";
  version = "0.0.0";

  src = ./../../../../software/ros_ws/src/perseus_autonomy_bridge;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    nav2-msgs
    perseus-interfaces
    rclcpp
    rclcpp-action
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Autonomy Widget Bridge";
    license = with lib.licenses; [ mit ];
  };
}
