# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  boost,
  hardware-interface,
  pluginlib,
  rclcpp,
  rclcpp-lifecycle,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-lite-hardware";
  version = "0.1.0";

  src = ./../../../../software/ros_ws/src/perseus_lite_hardware;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    boost
    hardware-interface
    pluginlib
    rclcpp
    rclcpp-lifecycle
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Hardware interface for Perseus Lite robot";
    license = with lib.licenses; [ mit ];
  };
}
