# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-input-config";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/perseus_input_config;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Config files for Perseus input nodes and launch files";
    license = with lib.licenses; [ mit ];
  };
}
