# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  actuator-msgs,
  ament-cmake,
  backward-ros,
  hi-can-raw,
  rclcpp,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-payloads";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/perseus_payloads;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    actuator-msgs
    backward-ros
    hi-can-raw
    rclcpp
    sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Payload-specific nodes and launch files for the Perseus Rover.";
    license = with lib.licenses; [ mit ];
  };
}
