# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  backward-ros,
  builtin-interfaces,
  geometry-msgs,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-interfaces";
  version = "0.0.0";

  src = ./../../../../software/ros_ws/src/perseus_interfaces;

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    backward-ros
    builtin-interfaces
    geometry-msgs
    rosidl-default-runtime
    sensor-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "Perseus custom message definitions";
    license = with lib.licenses; [ mit ];
  };
}
