# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-index-cpp,
  ament-lint-auto,
  ament-lint-common,
  builtin-interfaces,
  cv-bridge,
  geometry-msgs,
  onnxruntime,
  opencv,
  perseus-interfaces,
  rcl-interfaces,
  rclcpp,
  sensor-msgs,
  std-msgs,
  tf2,
  tf2-geometry-msgs,
  tf2-ros,
  visualization-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-vision";
  version = "0.0.0";

  src = ./../../../../software/ros_ws/src/perseus_vision;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    ament-index-cpp
    builtin-interfaces
    cv-bridge
    geometry-msgs
    onnxruntime
    opencv
    perseus-interfaces
    rcl-interfaces
    rclcpp
    sensor-msgs
    std-msgs
    tf2
    tf2-geometry-msgs
    tf2-ros
    visualization-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A package to do vision/detection tasks of Perseus";
    license = with lib.licenses; [ mit ];
  };
}
