# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  fast-lio,
  pcl-conversions,
  sensor-msgs,
  std-srvs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-mapping";
  version = "0.0.0";

  src = ./../../../../software/ros_ws/src/perseus_mapping;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    fast-lio
    pcl-conversions
    sensor-msgs
    std-srvs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Perseus package for 3D mapping and odometry using the Livox MID360 Lidar";
    license = with lib.licenses; [ mit ];
  };
}
