# Automatically generated by: ros2nix --output-dir=/home/huon/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  behaviortree-cpp,
  builtin-interfaces,
  geometry-msgs,
  rclcpp,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-bt-nodes";
  version = "0.0.0";

  src = ./../../../../software/ros_ws/src/perseus_bt_nodes;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    behaviortree-cpp
    builtin-interfaces
    geometry-msgs
    rclcpp
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Custom BehaviorTree nodes for Perseus waypoint navigation";
    license = with lib.licenses; [ mit ];
  };
}
