# Automatically generated by: ros2nix --output-dir=/home/bocho0600/roar/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  interfaces,
  pluginlib,
  qt5,
  rclcpp,
  rviz-common,
}:
buildRosPackage rec {
  pname = "ros-jazzy-rviz-plugins";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/rviz_plugins;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    interfaces
    pluginlib
    qt5.qtbase
    rclcpp
    rviz-common
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "RViz panels and displays for the rover's custom messages";
    license = with lib.licenses; [ mit ];
  };
}
