# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-index-cpp,
  ament-lint-auto,
  ament-lint-common,
  arena-server,
  geometry-msgs,
  interfaces,
  nav-msgs,
  pluginlib,
  qt5,
  rclcpp,
  rviz-common,
  std-srvs,
  tf2,
  tf2-geometry-msgs,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-rviz-plugins";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/rviz_plugins;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    ament-index-cpp
    arena-server
    geometry-msgs
    interfaces
    nav-msgs
    pluginlib
    qt5.qtbase
    rclcpp
    rviz-common
    std-srvs
    tf2
    tf2-geometry-msgs
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "RViz panels and displays for the rover's custom messages";
    license = with lib.licenses; [ mit ];
  };
}
