# Automatically generated by: ros2nix --output-dir=/home/bocho0600/roar/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  backward-ros,
  geometry-msgs,
  nav-msgs,
  rclcpp,
  rclcpp-components,
  realsense2-camera,
  realsense2-description,
  rplidar-ros,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-sensors";
  version = "0.1.0";

  src = ./../../../../software/ros_ws/src/sensors;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    backward-ros
    geometry-msgs
    nav-msgs
    rclcpp
    rclcpp-components
    realsense2-camera
    realsense2-description
    rplidar-ros
    sensor-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "ROS 2 sensor support for Perseus: IMU bias estimation and removal, a radius-based point cloud dust filter, a generic topic remapper, and the launch files and configuration for the RealSense and Livox sensors.";
    license = with lib.licenses; [ mit ];
  };
}
