# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  nix-ros-overlay ? builtins.fetchTarball "https://github.com/lopsided98/nix-ros-overlay/archive/master.tar.gz",
  pkgs ? import nix-ros-overlay { },
  rosDistro ? "jazzy",
  extraPkgs ? { },
  extraPaths ? [ ],
  withPackages ? _: [ ],
  extraShellHook ? "",
}:
pkgs.mkShell {
  name = "ros2nix ${rosDistro} shell";
  packages = [
    (pkgs.rosPackages.${rosDistro}.buildEnv {
      wrapPrograms = false;
      paths = [
        pkgs.colcon
        pkgs.rosPackages.${rosDistro}.ros-core

        # Work around https://github.com/lopsided98/nix-ros-overlay/pull/624
        pkgs.rosPackages.${rosDistro}.ament-cmake-core
        pkgs.rosPackages.${rosDistro}.python-cmake-module
      ]
      ++ (
        with pkgs;
        with pkgs.rosPackages.${rosDistro};
        with extraPkgs;
        [
          # Dependencies from package.xml files
          actuator-msgs
          ament-cmake
          ament-cmake-gen-version-h
          ament-cmake-gmock
          ament-cmake-gtest
          ament-cmake-python
          ament-index-cpp
          ament-index-python
          ament-lint-auto
          ament-lint-common
          backward-ros
          builtin-interfaces
          compressed-depth-image-transport
          compressed-image-transport
          control-msgs
          controller-manager
          controller-manager-msgs
          cv-bridge
          diff-drive-controller
          dynamixel-sdk
          fast-lio
          generate-parameter-library
          geometry-msgs
          grid-map-core
          hardware-interface
          hector-testing-utils
          hi-can
          hi-can-raw
          joint-state-broadcaster
          joint-state-publisher-gui
          joint-trajectory-controller
          joy
          liblapack
          mecanum-drive-controller
          moveit-core
          moveit-kinematics
          moveit-msgs
          moveit-planners-ompl
          moveit-ros-move-group
          moveit-ros-visualization
          moveit-servo
          moveit-simple-controller-manager
          nav-msgs
          navigation2
          nlohmann_json
          onnxruntime
          opencv
          orocos-kdl-vendor
          pcl-conversions
          pluginlib
          rcl-interfaces
          rclcpp
          rclcpp-components
          rclcpp-lifecycle
          rclpy
          realsense2-camera
          realsense2-description
          robot-localization
          robot-state-publisher
          ros2-control
          ros2-control-cmake
          ros2controlcli
          ros2launch
          rosidl-default-generators
          rosidl-default-runtime
          rplidar-ros
          rtest
          rviz2
          sensor-msgs
          slam-toolbox
          std-msgs
          std-srvs
          tf2
          tf2-eigen
          tf2-geometry-msgs
          tf2-kdl
          tf2-ros
          trajectory-msgs
          transmission-interface
          twist-mux
          v4l2-camera
          visualization-msgs
          xacro
        ]
      )
      ++ builtins.attrValues extraPkgs
      ++ extraPaths
      ++ withPackages (pkgs // pkgs.rosPackages.${rosDistro});
    })
  ];
  shellHook = ''
    # Setup ROS 2 shell completion. Doing it in direnv is useless.
    if [[ ! $DIRENV_IN_ENVRC ]]; then
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete ros2)"
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete colcon)"
    fi
  ''
  + extraShellHook;
}
