# Automatically generated by: ros2nix --output-dir=/home/runner/work/perseus-v3/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  actuator-msgs,
  ament-cmake,
  ament-cmake-python,
  backward-ros,
  geometry-msgs,
  joy,
  rclcpp,
  rclpy,
  sensor-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-teleop";
  version = "2.3.3";

  src = ./../../../../software/ros_ws/src/teleop;

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    ament-cmake-python
  ];
  propagatedBuildInputs = [
    actuator-msgs
    backward-ros
    geometry-msgs
    joy
    rclcpp
    rclpy
    sensor-msgs
  ];
  nativeBuildInputs = [
    ament-cmake
    ament-cmake-python
  ];

  meta = {
    description = "Teleoperation for Perseus: keyboard teleop node, generic joystick controller node, and controller configs.";
    license = with lib.licenses; [
      mit
      asl20
    ];
  };
}
