# Automatically generated by: ros2nix --output-dir=/home/brock/Projects/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  rclcpp,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-template-package";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/ros2;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [
    rclcpp
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Template Package";
    license = with lib.licenses; [ mit ];
  };
}
