# Automatically generated by: ros2nix --output-dir=/home/bocho0600/roar/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  geometry-msgs,
  interfaces,
  nav-msgs,
  rclcpp,
}:
buildRosPackage rec {
  pname = "ros-jazzy-watchdog";
  version = "0.0.1";

  src = ./../../../../software/ros_ws/src/nav-stack/watchdog;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    geometry-msgs
    interfaces
    nav-msgs
    rclcpp
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Runtime monitors that watch for unsafe or degraded robot behaviour";
    license = with lib.licenses; [ mit ];
  };
}
