# Automatically generated by: ros2nix --output-dir=/home/dan/perseus-v3/nix/extra-packages/ros-packages/perseus --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  rclcpp,
}:
buildRosPackage rec {
  pname = "ros-jazzy-workshop";
  version = "1.0.0";

  src = ./../../../../software/ros_ws/src/workshop;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ rclcpp ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "This is a workshop examples package";
    license = with lib.licenses; [ mit ];
  };
}
