# spellchecker:off
[files]
extend-exclude = [
  "typos.toml",
  "treefmt.toml",
  "hardware/**",
  "**/sdkconfig.*",
  "*.svg",
  "*.png",
  "*.drawio",
  "*.patch",
]

[default]

extend-ignore-re = [
  # see
  # https://github.com/crate-ci/typos/blob/master/docs/reference.md
  # for the origin of these two regexes
  # disable lines with trailing commented spellchecker:disable-line
  "(?Rm)^.*(?:#|//|%).*spellchecker:\\s*disable-line$",
  # disable blocks between spellchecker:off and spellchecker:on
  "(?s)(?:#|//|%)\\s*spellchecker:\\s*off.*?\\n\\s*(?:#|//|%)\\s*spellchecker:\\s*on",
]

[default.extend-words]
area_sizez = "area_sizez"
sizez = "sizez"
substituters = "substituters"
# Perspective-n-Point (computer vision algorithm, e.g. cv::solvePnP)
Pn = "Pn"

# unfortunately we need to use American spelling in code
[type.cpp]
extend-words = { serialise = "serialize", deserialise = "deserialize", centre = "center" }

[type.py]
extend-words = { serialise = "serialize", deserialise = "deserialize" }

[type.md]
extend-words = { ros = "ROS" }
extend-ignore-re = [
  "ROS",
  # align: center (for inserting images)
  "(?Rm)^\\s*:?align:\\s*center$",
  # inline code snippets
  "`.+?`",
  "<.+?>",
  # code blocks (should never be more than 3 levels deep hopefully)
  "(?Rms)^\\s*`{5}[^`]*$.*?^\\s*`{5}$",
  "(?Rms)^\\s*`{4}[^`]*$.*?^\\s*`{4}$",
  "(?Rms)^\\s*`{3}[^`]*$.*?^\\s*`{3}$",
  # links
  "\\]\\(.*\\)",
  # package/directory names (though they should be in backticks anyway)
  "\\w*(?:-|_)\\w*",
]
# spellchecker:on
