# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  geometry-msgs,
  joy,
  python3Packages,
  rclpy,
  sensor-msgs,
  teleop-twist-joy,
  teleop-twist-keyboard,
}:
buildRosPackage rec {
  pname = "ros-jazzy-input-devices";
  version = "0.0.1";

  src = ./../src/input_devices;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    geometry-msgs
    joy
    python3Packages.pygame
    rclpy
    sensor-msgs
    teleop-twist-joy
    teleop-twist-keyboard
  ];

  meta = {
    description = "Nodes and launch files for handling input devices";
    license = with lib.licenses; [ mit ];
  };
}
