# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-cmake,
  backward-ros,
  hardware-interface,
  hi-can,
  hi-can-raw,
  pluginlib,
  rclcpp,
  rclcpp-lifecycle,
}:
buildRosPackage rec {
  pname = "ros-jazzy-perseus-hardware";
  version = "0.0.1";

  src = ./../src/perseus_hardware;

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    hi-can-raw
  ];
  propagatedBuildInputs = [
    backward-ros
    hardware-interface
    hi-can
    pluginlib
    rclcpp
    rclcpp-lifecycle
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Perseus rover hardware interface plugins for ROS2 control";
    license = with lib.licenses; [ mit ];
  };
}
