# Automatically generated by: ros2nix --output-dir=ros_ws/nix-packages --output-as-nix-pkg-name --no-default --distro jazzy
{
  lib,
  buildRosPackage,
  ament-copyright,
  ament-flake8,
  ament-pep257,
  geometry-msgs,
  python3Packages,
  rclpy,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-teleop-diagnostics";
  version = "0.1.0";

  src = ./../src/teleop_diagnostics;

  buildType = "ament_python";
  checkInputs = [
    ament-copyright
    ament-flake8
    ament-pep257
    python3Packages.pytest
  ];
  propagatedBuildInputs = [
    geometry-msgs
    rclpy
    sensor-msgs
    std-msgs
  ];

  meta = {
    description = "TUI diagnostic tool for teleoperation debugging";
    license = with lib.licenses; [ mit ];
  };
}
