# Automatically generated by: ros2nix --fetch --output-as-nix-pkg-name --distro=jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  common-interfaces,
  geometry-msgs,
  livox-ros-driver2,
  nav-msgs,
  pcl-conversions,
  pcl-ros,
  rclcpp,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
  std-msgs,
  tf2,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-fast-lio";
  version = "0.0.0";

  # Fork of hku-mars/FAST_LIO. It carries what used to live in
  # ../patches/fast-lio: the C++17 bump Jazzy needs, and the TF frame names /
  # TF-publishing switches turned into ROS parameters (common.map_frame,
  # common.body_frame, common.lid_frame, publish.tf_en, publish.tf_lidar_en).
  #
  # fetchSubmodules is required: the ikd-Tree implementation is a git submodule.
  # Pinned to a commit rather than a branch name, since fetchFromGitHub does not
  # track a moving ref and a bare branch would silently change what gets built.
  #
  # To move the pin, push the fork and re-read both values from:
  #   nix-prefetch-git --url https://github.com/bocho0600/FAST_LIO \
  #     --rev <commit> --fetch-submodules
  src = fetchFromGitHub {
    owner = "bocho0600";
    repo = "FAST_LIO";
    rev = "1af4dbeaa9c1e813f2a72ce5b69299ff8aaf85d4"; # feat/origin-heading
    hash = "sha256-9DVAabV20elZq438iCktoZJXpWY60yzUfyClFj3wwN8=";
    fetchSubmodules = true;
  };

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  propagatedBuildInputs = [
    common-interfaces
    geometry-msgs
    livox-ros-driver2
    nav-msgs
    pcl-conversions
    pcl-ros
    rclcpp
    rosidl-default-runtime
    sensor-msgs
    std-msgs
    tf2
    # the fork find_package()s tf2_ros explicitly for the (static) transform broadcasters
    tf2-ros
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "This is a modified version of LOAM which is original algorithm
    is described in the following paper:
    J. Zhang and S. Singh. LOAM: Lidar Odometry and Mapping in Real-time.
    Robotics: Science and Systems Conference (RSS). Berkeley, CA, July 2014.";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
