# Automatically generated by: ros2nix --fetch --output-as-nix-pkg-name --distro=jazzy
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  common-interfaces,
  geometry-msgs,
  livox-ros-driver2,
  nav-msgs,
  pcl-conversions,
  pcl-ros,
  rclcpp,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
  std-msgs,
  tf2,
}:
buildRosPackage rec {
  pname = "ros-jazzy-fast-lio";
  version = "0.0.0";

  src = fetchFromGitHub {
    owner = "hku-mars";
    repo = "FAST_LIO";
    rev = "a4743b095409588842a5b30ddfa27e29d2f99164";
    sha256 = "0cslk11hskmdclbpkargk198p13fcgmb9l0bfnm601sjimc9r203";
  };

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake
    rosidl-default-generators
  ];
  propagatedBuildInputs = [
    common-interfaces
    geometry-msgs
    livox-ros-driver2
    nav-msgs
    pcl-conversions
    pcl-ros
    rclcpp
    rosidl-default-runtime
    sensor-msgs
    std-msgs
    tf2
  ];
  nativeBuildInputs = [
    ament-cmake
    rosidl-default-generators
  ];

  meta = {
    description = "This is a modified version of LOAM which is original algorithm
    is described in the following paper:
    J. Zhang and S. Singh. LOAM: Lidar Odometry and Mapping in Real-time.
    Robotics: Science and Systems Conference (RSS). Berkeley, CA, July 2014.";
    license = with lib.licenses; [ bsdOriginal ];
  };
}
