# Automatically generated by: ros2nix --output-as-nix-pkg-name --distro jazzy --fetch package_ROS2.xml
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake-auto,
  ament-lint-auto,
  ament-lint-common,
  apr,
  git,
  pcl,
  pcl-conversions,
  rcl-interfaces,
  rclcpp,
  rclcpp-components,
  rcutils,
  rosbag2,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-livox-ros-driver2";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "Livox-SDK";
    repo = "livox_ros_driver2";
    rev = "6b9356cadf77084619ba406e6a0eb41163b08039";
    sha256 = "1r85jzrh9j5x7c5dwlb8mzhpsfv41brm6n83l0f9k3z462ww2q8z";
  };

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake-auto
    rosidl-default-generators
  ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    apr
    git
    pcl
    pcl-conversions
    rcl-interfaces
    rclcpp
    rclcpp-components
    rcutils
    rosbag2
    rosidl-default-runtime
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The ROS device driver for Livox 3D LiDARs, for ROS2";
    license = with lib.licenses; [ mit ];
  };
}
