# Automatically generated by: ros2nix --output-as-nix-pkg-name --distro jazzy --fetch
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-lint-auto,
  ament-lint-common,
  behaviortree-cpp,
  geometry-msgs,
  nav-msgs,
  nav2-behavior-tree,
  nav2-core,
  nav2-msgs,
  nav2-util,
  opennav-coverage-msgs,
  rclcpp,
  rclcpp-action,
}:
buildRosPackage rec {
  pname = "ros-jazzy-opennav-coverage-bt";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "open-navigation";
    repo = "opennav_coverage";
    rev = "194250501889ce8896c5ee8b80a4d1317750be0e";
    sha256 = "0nqi8d99qs9cqb22x66kzzf9zgylayji0ibpg0ff47plwx32zs0l";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/opennav_coverage_bt/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    behaviortree-cpp
    geometry-msgs
    nav-msgs
    nav2-behavior-tree
    nav2-core
    nav2-msgs
    nav2-util
    opennav-coverage-msgs
    rclcpp
    rclcpp-action
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A set of BT nodes and XMLs for complete coverage planning";
    license = with lib.licenses; [ asl20 ];
  };
}
