# Automatically generated by: ros2nix --output-as-nix-pkg-name --distro jazzy --fetch
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake,
  ament-index-cpp,
  ament-lint-auto,
  ament-lint-common,
  builtin-interfaces,
  fields2cover,
  geometry-msgs,
  nav-msgs,
  nav2-msgs,
  nav2-util,
  opennav-coverage-msgs,
  rclcpp,
  rclcpp-action,
  rclcpp-lifecycle,
  tf2-ros,
}:
buildRosPackage rec {
  pname = "ros-jazzy-opennav-coverage";
  version = "0.0.1";

  src = fetchFromGitHub {
    owner = "open-navigation";
    repo = "opennav_coverage";
    rev = "194250501889ce8896c5ee8b80a4d1317750be0e";
    sha256 = "0nqi8d99qs9cqb22x66kzzf9zgylayji0ibpg0ff47plwx32zs0l";
  };

  buildType = "ament_cmake";
  sourceRoot = "${src.name}/opennav_coverage/";
  buildInputs = [ ament-cmake ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    ament-index-cpp
    builtin-interfaces
    fields2cover
    geometry-msgs
    nav-msgs
    nav2-msgs
    nav2-util
    opennav-coverage-msgs
    rclcpp
    rclcpp-action
    rclcpp-lifecycle
    tf2-ros
  ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "A Task Server for complete coverage planning";
    license = with lib.licenses; [ asl20 ];
  };
}
