rosDistro: final: prev:
let
  # ros2nix autogenerated package overlay location
  localPackagingOverlay = import ./nix-packages/overlay.nix;
  rosPkgsOverlay =
    rosFinal: rosPrev:
    # use composeManyExtensions to "combine" the overlays in the order specified
    (prev.lib.composeManyExtensions [
      # add all the workspace packages to the output ros package set
      localPackagingOverlay
      (
        rosFinal: rosPrev:
        let
          /*
            The intersection of the full custom package set and the workspace packages overlay
            selects the fully resolved packages out of the custom package set,
            getting us only the dev packages.

            That then gets merged with the colcon-ignore package so colcon doesn't try
            and build things from the (already built!) result symlink that nix build generates
          */
          allDevPackages = (builtins.intersectAttrs (localPackagingOverlay null null) rosFinal) // {
            inherit (prev) colcon-ignore; # always include colcon-ignore in dev packages
          };
          /*
            However, for the final output, we want to remove simulation packages,
            so people don't download gazebo if they don't need to
          */
          devPackages = removeAttrs allDevPackages [ "perseus-simulation" ];
          # just take the ones we *removed* from devPackages
          simDevPackages = removeAttrs allDevPackages (builtins.attrNames devPackages);
        in
        {
          inherit devPackages simDevPackages;
          # wrap gz and rviz with nixGL
          rviz2-fixed = prev.writeShellScriptBin "rviz2-fixed" ''
            ${final.nixgl-script} "${prev.lib.getExe rosPrev.rviz2}" "$@"
          '';
          gz-sim-fixed = prev.writeShellScriptBin "gz-sim-fixed" ''
            ${final.nixgl-script} gz sim "$@"
          '';
        }
      )
    ] rosFinal rosPrev);
in
prev.lib.composeManyExtensions [
  (final: prev: {
    rosPackages = prev.rosPackages // {
      ${rosDistro} = prev.rosPackages.${rosDistro}.overrideScope rosPkgsOverlay;
    };
  })
  (import ./patches.nix rosDistro)
] final prev
