name: "CI/CD"
on:
  push: # any push ignoring push actions triggered by merge queue
    branches-ignore:
      - gh-readonly-queue/**
  pull_request: # run when pr is opened
  merge_group: # run when pr enters the merge queue
  workflow_dispatch: # run manually
permissions:
  contents: read # only read as write is specified for jobs as necessary
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # defines a concurrentcy group key
  cancel-in-progress: true # only allow one job with this group key at a time
jobs:
  # Define global variables used by other jobs
  global-vars:
    name: Setup global variables
    runs-on: ubuntu-latest
    outputs:
      # Define messages used when committing changes from actions
      format-msg: ${{ steps.export-vars.outputs.format-msg }}
      package-msg: ${{ steps.export-vars.outputs.package-msg }}
      # Only want to deploy docs from the main branch
      is-main: ${{ (github.repository == 'ROAR-QUTRC/perseus-v2') && (github.ref == 'refs/heads/main') }}
      # We don't want to run commit actions on pull request workflows (ie, after the merge commit),
      # only on push and manual dispatch, so all commit+push steps are filtered by the event name
      can-push-commits: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
      # Auth secrets
      has-cachix-secret: ${{ secrets.CACHIX_AUTH_TOKEN != '' }}
      has-repo-secret: ${{ secrets.REPO_DEPLOY_KEY != '' }}
    steps:
      - name: Export Nix config
        id: export-vars
        run: |
          {
            echo "format-msg=chore: Format and lint"
            echo "package-msg=chore: Update Nix packaging"
          } >> "$GITHUB_OUTPUT"
          {
            echo "format-msg=chore: Format and lint"
            echo "package-msg=chore: Update Nix packaging"
          } >> "$GITHUB_OUTPUT"
  # get the file changes to filter other jobs
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      # Manual overrides most of the following filters
      manual: ${{ github.event_name == 'workflow_dispatch'}}
      software: ${{ steps.filter.outputs.software }}
      docs: ${{ steps.filter.outputs.docs }}
      # Regenerate ros2 packages
      packages: ${{ steps.filter.outputs.packages }}
      # Determined based on the last commit message, see below
      skip-format: ${{ steps.previous-format.outputs.skip }}
      skip-package: ${{ steps.previous-package.outputs.skip }}
    needs: global-vars
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: .github/filters.yaml
      - name: Check for previous formatting
        id: previous-format
        # WARNING: The commit message check is fragile and may break if the commit
        # message changes, hence it's determined by the global-vars job.
        # We can skip the format job if the last message was a format *or*
        # package message, since package will always run after format
        run: |
          case "$(git log -1 --pretty=format:%B)" in
            "${{ needs.global-vars.outputs.package-msg }}"|"${{ needs.global-vars.outputs.format-msg }}")
              echo "skip=true" >> "$GITHUB_OUTPUT"
              echo "Format job will be skipped since the last commit was a format or package commit"
              ;;
            *)
              echo "skip=false" >> "$GITHUB_OUTPUT"
              echo "Format job will run"
              ;;
          esac
      - name: Check for previous packaging
        id: previous-package
        # same thing as the format check job
        run: |
          if [ "$(git log -1 --pretty=format:%B)" = "${{ needs.global-vars.outputs.package-msg }}" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "Package job will be skipped since the last commit was a package commit"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "Package job will run"
          fi;
  # Regenerate ROS2 Nix packages using `ros2nix` if any of the `package.xml` files have changed
  package:
    name: Generate ROS2 Nix packages
    if: ${{ !cancelled() && (needs.changes.outputs.skip-package != 'true') && (needs.changes.outputs.packages == 'true') && (needs.global-vars.outputs.can-push-commits == 'true') }}
    needs: [global-vars, changes]
    runs-on: ubuntu-latest
    permissions:
      # Needed to commit to the repo
      contents: write
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      # Configure read only caches, will write to cachix below
      - uses: cachix/cachix-action@v17
        with:
          name: roar
          extraPullNames: ros
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      - name: Generate packages
        # Don't automatically commit for commit message consistency, see comment above in 'changes' job
        run: devenv shell generate-ros-pkgs --no-commit
      - uses: stefanzweifel/git-auto-commit-action@v7
        name: Commit and push changes
        with:
          commit_message: ${{ needs.global-vars.outputs.package-msg }}
  build-env:
    name: Build environment
    needs: [global-vars, changes, package]
    # Build for x86 and arm
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      # Configure the roar cachix and use the ros cachix as an upstream substitutor
      # The devenv cache is automatically as well when devenv is installed
      - uses: cachix/cachix-action@v17
        if: needs.global-vars.outputs.has-cachix-secret == 'true'
        with:
          name: roar
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: ros
      # Collect garbage from nix2ros so it doesn't get pushed to cache by the build-env job
      - name: Garbage collect
        run: nix-collect-garbage -d
      - name: Install devenv.sh
        run: nix profile add nixpkgs#devenv
      # `test` will build the environment and run all tests
      - name: Build and test environment
        run: devenv --profile cicd test
  debug:
    name: Debug
    needs: [global-vars, changes]
    runs-on: ubuntu-latest
    steps:
      - name: print global variables
        run: |
          echo "format-msg=${{ needs.global-vars.outputs.format-msg }}"
          echo "package-msg=${{ needs.global-vars.outputs.package-msg }}"
          echo "is-main=${{ needs.global-vars.outputs.is-main }}"
          echo "has-cachix-secret=${{ needs.global-vars.outputs.has-cachix-secret }}"
          echo "has-repo-secret=${{ needs.global-vars.outputs.has-repo-secret }}"
          echo "can-push-commits=${{ needs.global-vars.outputs.can-push-commits }}"
      - name: print changed files
        run: |
          echo "manual=${{ needs.changes.outputs.manual }}"
          echo "software=${{ needs.changes.outputs.software }}"
          echo "docs=${{ needs.changes.outputs.docs }}"
          echo "packages=${{ needs.changes.outputs.packages }}"
          echo "skip-format=${{ needs.changes.outputs.skip-format }}"
          echo "skip-package=${{ needs.changes.outputs.skip-package }}"
