# Automatically generated by: ros2nix --output-as-nix-pkg-name --distro jazzy --fetch
{
  lib,
  buildRosPackage,
  fetchFromGitHub,
  ament-cmake-auto,
  ament-lint-auto,
  ament-lint-common,
  apr,
  git,
  pcl,
  pcl-conversions,
  rcl-interfaces,
  rclcpp,
  rclcpp-components,
  rcutils,
  rosbag2,
  rosidl-default-generators,
  rosidl-default-runtime,
  sensor-msgs,
  std-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-livox-ros-driver2";
  version = "1.0.0";

  src = fetchFromGitHub {
    owner = "Livox-SDK";
    repo = "livox_ros_driver2";
    rev = "b6ff7d1c8b210a96b74e919823771e1e32249758";
    sha256 = "0i11hyb3rsqqsmdzx8gas0yb71053jh9bzl2hvzq0iaajyzad7g9";
  };

  buildType = "ament_cmake";
  buildInputs = [
    ament-cmake-auto
    rosidl-default-generators
  ];
  checkInputs = [
    ament-lint-auto
    ament-lint-common
  ];
  propagatedBuildInputs = [
    apr
    git
    pcl
    pcl-conversions
    rcl-interfaces
    rclcpp
    rclcpp-components
    rcutils
    rosbag2
    rosidl-default-runtime
    sensor-msgs
    std-msgs
  ];
  nativeBuildInputs = [ ament-cmake-auto ];

  meta = {
    description = "The ROS device driver for Livox 3D LiDARs, for ROS2";
    license = with lib.licenses; [ mit ];
  };
}
